services:
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: citymapper
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5

    meilisearch:
        image: getmeili/meilisearch:latest
        restart: always
        ports:
            - "7700:7700"
        volumes:
            - ./meili_data:/meili_data
        environment:
            MEILI_MASTER_KEY: YOUR_MEILISEARCH_TOKEN
        healthcheck:
            test: ["CMD-SHELL", "curl -s http://localhost:7700/health"]
            interval: 10s
            timeout: 5s
            retries: 5

    migration:
        restart: on-failure
        build:
            context: ./server
            dockerfile: Dockerfile.migration
        ports:
            - "8000:8000"
        depends_on:
            postgres:
                condition: service_healthy
            meilisearch:
                condition: service_healthy
        environment:
            DATABASE_URL: postgres://postgres:postgres@postgres/citymapper
            MEILI_HOST: http://meilisearch:7700
        command: >
            /bin/sh -c "
            until pg_isready -h postgres -p 5432; do
                sleep 1;
            done;
            diesel migration run &&
            ./target/release/setup_db AddAll &&
            ./target/release/setup_meilisearch &&
            ./target/release/setup_db CorrectStops
            "

    backend:
        restart: on-failure
        build:
            context: ./server
        ports:
            - "127.0.0.1:8000:8000"
        depends_on:
            - postgres
            - meilisearch
        environment:
            DATABASE_URL: postgres://postgres:postgres@postgres/citymapper
            ROCKET_PORT: 8000
            ROCKET_ADDRESS: "0.0.0.0"
        command: ["./target/release/citymapper-server"]

    frontend:
        restart: on-failure
        build:
            context: ./client
        ports:
            - "4173:4173"
        depends_on:
            - backend
        environment:
            VITE_REACT_APP_MAPBOX_URL: YOUR_MAPBOX_URL
            VITE_REACT_APP_MAPBOX_URL_DARK: YOUR_MAPBOX_URL
            VITE_REACT_APP_MAPBOX_TOKEN: YOUR_MAPBOX_TOKEN
            VITE_REACT_MEILISEARCH_TOKEN: YOUR_MEILISEARCH_TOKEN
            VITE_BASE_API_LINK: YOUR_API_LINK
            VITE_MEILISEARCH_API_LINK: YOUR_MEILISEARCH_API_LINK

volumes:
    postgres_data:
    meili_data:
